### ISSUE TITLE
Holobar not hiding glyphs properly

### ISSUE THREAD

**Issue by StephenHodgson** [Microsoft/MRDesignLabs_Unity#3] opened 2017-05-30 15:07 UTC
![image](https://cloud.githubusercontent.com/assets/13334553/26592076/b14787b0-452d-11e7-966e-2edc2ca38518.png)
![image](https://cloud.githubusercontent.com/assets/13334553/26592120/d0688bf8-452d-11e7-9d6e-55b90340d32f.png)

**Comment by Railboy** [comment] 2017-05-30 20:02
This has been fixed (changes will be committed shortly). 'AlphaColorProperty' will now default to '_Color' if not set, and 'None' is no longer a selectable option in the inspector.

Duplicate of [App bar shows unexpected glyphs.](https://github.com/Microsoft/MRDesignLabs_Unity/issues/2)

**Closed by Railboy** 2017-05-30 20:02 UTC
Labels: bug, duplicate
