### ISSUE TITLE
Cannot manipulate game objects using bounding box handles

### ISSUE THREAD

**Issue by MichaelReiter** [Microsoft/MRDesignLabs_Unity#22] opened 2017-07-05 22:35 UTC
# The Issue
I'm trying to resize and/or rotate an object in the ManipulationGizmo_Examples scene, but the handles on the bounding box are not active for me.

# What I tried
I configured the project in Unity as referenced [here](https://github.com/Microsoft/MRDesignLabs_Unity/tree/master/DesignLabs_Unity_Examples#app-bar--bounding-box).
- In the Unity editor I can move the camera using the arrow keys, look around by holding down the right mouse button and interact with the AppBar menu buttons with the left mouse button when the cursor is over them. However, the BoundingBoxShell handles are not active (dark blue color instead of light blue) and I cannot interact with them.
- I built the solution in Visual Studio and deployed the app to a HoloLens. I can look around and select objects using the finger tap selection gesture, but again the handles are not active.
- I deployed to an Acer Developer Edition Windows Mixed Reality headset, but the same issue persists.

# Further investigation
It appears the manipulation gesture is not firing. In BoundingBoxManipulate.cs, my breakpoint in `OnManipulationStarted()` is not being hit, but further breakpoints on other events (tap, hold, etc.) are being hit.

Perhaps the events are not wired up correctly in some way or I'm misunderstanding how to interact with the GameObject. Any help is appreciated.

**Comment by Railboy** [comment] 2017-07-06 18:09
You're doing everything correctly as far as I can tell. I've been looking through your project settings and I see no obvious cause for this problem.

The only _potential_ cause I see is that your project uses Unity 5.6.2f1, not 5.6.1f1, which is the latest version that MRDL has been tested with. However I see nothing in the changelog that stands out to me. I'll try running the project in 5.6.2f1 and see if I can reproduce the issue.

Anyone have any theories?

**Comment by Railboy** [comment] 2017-07-07 17:34
Just tried to use the manipulation gizmo on the device in a 5.6.2f1 build and was able to get Manipulation events to fire. This was with a freshly checked-out copy of the MRDesignLabs_Unity project. So we can rule that out.

**Comment by MichaelReiter** [comment] 2017-07-07 17:37
That's very curious because I just did the same thing yesterday. What gesture/input method did you use to interact? Left mouse button in the Unity editor I presume?

**Comment by Railboy** [comment] 2017-07-07 17:42
I used tap-drag with my hand on the HoloLens device.

**Comment by MichaelReiter** [comment] 2017-07-07 20:14
Interesting, it is working for me now in HoloLens with the tap-drag gesture, but I not in the Unity editor. How do I trigger that gesture with a keyboard/mouse?

**Comment by Railboy** [comment] 2017-07-09 01:23
> Interesting, it is working for me now in HoloLens with the tap-drag gesture
Glad to hear that. If you have any insight into what might have changed let us know.

Now that we know regular gesture input functions for you I'll check in with our engineers about mouse input. I know that mouse / gamepad driven gestures were in the works but they may not be functional yet.

**Comment by MichaelReiter** [comment] 2017-07-10 16:35
Thanks for the update. I don't know why it works with the tap-drag gesture now when it didn't previously. All I did was a fresh clone.

**Comment by Railboy** [comment] 2017-07-12 23:03
Some changes to the manipulation code were recently committed to the Tools submodule that should re-enable mouse-driven gesture simulation. Let us know if this fixes the issue for you.

**Comment by Railboy** [comment] 2017-07-12 23:11
Looks like I jumped the gun on my earlier comment. An manipulation update is incoming; I'll post again when it's been committed to the main submodule.

**Comment by HattMarris1** [comment] 2017-07-13 15:35
Is manipulation supposed to work with the clicker? When using the bounding box, I am able to manipulate it by air tapping and holding then moving my hand, but not with the clicker.

(apologies in advance if I'm missing something obvious, I'm very new to this)

**Comment by Railboy** [comment] 2017-07-18 21:32
Michael - those changes have been committed to the main submodule and have been propagated to this project. Give it a try and let us know how it goes.

The clicker should benefit from these changes as well - if it still gives you trouble after downloading the latest go ahead and open a new issue.

**Comment by MichaelReiter** [comment] 2017-07-19 17:13
My team is no longer using this project, but I appreciate the update. Thanks for looking into it for me.

**Comment by paseb** [comment] 2017-07-19 17:28
@HattMarris1 the clicker has it's own issue.  Currently it will only give you and +-45 degree from the interaction start and you don't really get raw IMU data, which is unfortunate.  It also looks like I had removed the clicker input source from our input mapping.  I'll add it back so that we have clicker support in the input sources again.

**Comment by Railboy** [comment] 2017-07-19 19:07
@HattMarris1 feel free to open a new issue for the clicker. I'm going to close this issue to keep the topics separate.

**Closed by Railboy** 2017-07-19 19:07 UTC
Labels: bug, help wanted
